version: '1.0'
x-aws-vpc: "vpc-0440231913e013555"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - todo-database
    ports:
      - "3000:5000"  # Map host port 9000 to container port 9000


  todo-database:
    image: mongo:6
    volumes:
      - database:/data/db  # Mount a volume for MongoDB data storage
    ports:
      - "27017:27017"  # Map host port 27017 to container port 27017

volumes:
  database:  # Define a named volume for MongoDB data storage


