version: '1.0'
x-aws-vpc: "vpc-0440231913e013555"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:9000"  # Map host port 9000 to container port 9000
    volumes:
      - database:/data/db  # Mount a volume for MongoDB data storage
    env_file: .env

volumes:
  database:  # Define a named volume for MongoDB data storage


